//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perceiveit.Data.UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Perceiveit.Data.UnitTests.SampleData", typeof(SampleData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID, Title, Credits, Department, Description
        ///CPPG, Computer Programming, 1.0, IT, A starter programming course covering the basics
        ///CPL2, Advanced Programming, 2.0, IT, Advanced programing including patterns and frameworks
        ///CPNN, Neural Networks, 2.0, IT, Neural network programming - must have completed CPPG and CPL2 to start this one
        ///ENGM, Mechanical engineering basics, 1.0, Engineering, Basic mechanical engineering course
        ///ENGE, Electrical engineering 101, 1.0, Engineering, Basic Electrical engineering c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name, Budget, Admin
        ///IT, 200000.00, John Smith
        ///Engineering, 400000.00, Peter Jones
        ///Media Studies, 100000.00, Sarah Falls.
        /// </summary>
        internal static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course, Instructor
        ///CPPG, John Smith
        ///CPNN, John Smith
        ///CPNN, Beverly Knight
        ///ENGM, Peter Jones
        ///ENGE, Peter Jones
        ///ENGF, Peter Jones
        ///MSPH, Sarah Falls
        ///MSJO, Sarah Falls
        ///MSPS, Alex Mc&apos;allen.
        /// </summary>
        internal static string Instructors {
            get {
                return ResourceManager.GetString("Instructors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id, Url
        ///MSPH, http://myuniversity.com/courses/photography
        ///MSJO, http://myuniversity.com/courses/journalism.
        /// </summary>
        internal static string OnlineCourses {
            get {
                return ResourceManager.GetString("OnlineCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID, Location, Days, Time
        ///CPPG, North Wing, 15, 09:00:00
        ///CPL2, North Wing, 30, 13:00:00
        ///CPNN, North Wing, 30, 09:00:00
        ///ENGM, West Wing, 15, 10:00:00
        ///ENGE, West Wing, 15, 10:00:00
        ///ENGF, West Wing, 30, 13:00:00
        ///MSPS, Media Room, 15, 11:00:00.
        /// </summary>
        internal static string OnsiteCourses {
            get {
                return ResourceManager.GetString("OnsiteCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, Last, HireDate, Enrollment
        ///John, Smith, 2010-06-01, 2010-07-01
        ///Peter, Jones, 2007-04-17, 2007-04-17
        ///Sarah, Falls, 2009-12-01, NULL
        ///Alex, Mc&apos;allen, 2005-11-02,2005-11-02
        ///Beverly, Knight, 2006-12-02, 2006-12-01
        ///John, Knight, NULL, NULL.
        /// </summary>
        internal static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
    }
}
