/*  Copyright 2012 PerceiveIT Limited
 *  This file is part of the Scryber library.
 *
 *  You can redistribute Scryber and/or modify 
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  Scryber is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with Scryber source code in the COPYING.txt file.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scryber {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scryber.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font with name &apos;{0}&apos; is not a standard font, This font must be referenced in the configuration file or have the file path specified. .
        /// </summary>
        internal static string AFontWithNameMustBeDeclaredInConfig {
            get {
                return ResourceManager.GetString("AFontWithNameMustBeDeclaredInConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Component with the id &apos;{0}&apos; does not implement the IPDFDataSource interface. All Components that are to be used as datasources must implement this interface..
        /// </summary>
        internal static string AssignedDataSourceIsNotIPDFDataSource {
            get {
                return ResourceManager.GetString("AssignedDataSourceIsNotIPDFDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assigned datasource for the binding component does not implement the IXPathNavigable interface. All datasources that are to be used must implement this interface..
        /// </summary>
        internal static string AssignedDataSourceIsNotNavigable {
            get {
                return ResourceManager.GetString("AssignedDataSourceIsNotNavigable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access the offset {0} in the table with a {1} count of {2}.
        /// </summary>
        internal static string CannotAccessGridOffsetInTable {
            get {
                return ResourceManager.GetString("CannotAccessGridOffsetInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access the stream until its initial position has been set. Please use the Read() method before tring to access the stream..
        /// </summary>
        internal static string CannotAccessStreamWithoutRead {
            get {
                return ResourceManager.GetString("CannotAccessStreamWithoutRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add the cell reference to the column at row {0} because it is already full. Ensure that the cells are added in order to a column..
        /// </summary>
        internal static string CannotAddCellToIndexAlreadyFull {
            get {
                return ResourceManager.GetString("CannotAddCellToIndexAlreadyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The created style item returned from the Document could not be cast to a {0} item..
        /// </summary>
        internal static string CannotCastToStyleItem {
            get {
                return ResourceManager.GetString("CannotCastToStyleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of property &apos;{0}&apos; cannot be changed because the item &apos;{1}&apos; is locked for rendering.
        /// </summary>
        internal static string CannotChangeValueWhenLocked {
            get {
                return ResourceManager.GetString("CannotChangeValueWhenLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object of type &apos;{0}&apos; cannot be cast to the required &apos;{1}&apos; type..
        /// </summary>
        internal static string CannotConvertObjectToType {
            get {
                return ResourceManager.GetString("CannotConvertObjectToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of type &apos;{0}&apos; could not be created. {1}.
        /// </summary>
        internal static string CannotCreateInstanceOfType {
            get {
                return ResourceManager.GetString("CannotCreateInstanceOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method must be called with an absolute path (not relative). Use the MapPath method to attempt conversion from a relative to an absolute path..
        /// </summary>
        internal static string CannotLoadFileWithRelativePath {
            get {
                return ResourceManager.GetString("CannotLoadFileWithRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This group of table grid sizes has been locked and cannot be modified, only read..
        /// </summary>
        internal static string CannotModifyTableGridSizes {
            get {
                return ResourceManager.GetString("CannotModifyTableGridSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is an error to attempt to read past the end of the stream. Use the bool Read() return value before accessing the stream values..
        /// </summary>
        internal static string CannotReadPastTheEOF {
            get {
                return ResourceManager.GetString("CannotReadPastTheEOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base text value of the PageNumberLabel cannot be set explicity. This is derived at render time from the format value and current page numbers.
        /// </summary>
        internal static string CannotSetBaseTextOfPageNumber {
            get {
                return ResourceManager.GetString("CannotSetBaseTextOfPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set both the DataSource value and the DataSourceID value of a binding control. Ensure that the unused property is clear before setting the required property..
        /// </summary>
        internal static string CannotSetDataSourceAndDataSourceID {
            get {
                return ResourceManager.GetString("CannotSetDataSourceAndDataSourceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting of the &apos;Template&apos; property is not supported in the PDFChoose Component. Use the Where and Otherwise properties instead..
        /// </summary>
        internal static string CannotUseBaseTemplateInChoose {
            get {
                return ResourceManager.GetString("CannotUseBaseTemplateInChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use the FindComponent method when an Component is not contained within the document heirarchy..
        /// </summary>
        internal static string CannotUseFindForComponentNotInDocumentHeirarchy {
            get {
                return ResourceManager.GetString("CannotUseFindForComponentNotInDocumentHeirarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All external defined files must have a base type of &apos;{0}&apos;..
        /// </summary>
        internal static string CanOnlyReferenceExternalStyleDefinitionsOfType {
            get {
                return ResourceManager.GetString("CanOnlyReferenceExternalStyleDefinitionsOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parsed documents have a circular dependancy reference to the path &apos;{0}&apos;. Please check the references..
        /// </summary>
        internal static string CircularReferenceToPath {
            get {
                return ResourceManager.GetString("CircularReferenceToPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color space &apos;{0}&apos; is not supported. The PDFX graphics system currently only supports RGB and Gray color spaces, other values of the enumeration are there for future use..
        /// </summary>
        internal static string ColorValueIsNotCurrentlySupported {
            get {
                return ResourceManager.GetString("ColorValueIsNotCurrentlySupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Component with type &apos;{0}&apos; is not a known Component for the layout engine. Either change its type, make the type implement the IPDFComponentViewPort interface, or sets its type to NoOp..
        /// </summary>
        internal static string ComponentIsNotKnownToLayoutEngine {
            get {
                return ResourceManager.GetString("ComponentIsNotKnownToLayoutEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TableGrid could not be built for the table &apos;{0}&apos;. See the inner exception for more details.
        /// </summary>
        internal static string CouldNotBuildTheTableGrid {
            get {
                return ResourceManager.GetString("CouldNotBuildTheTableGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not fill the graphics context with the specific text due to the error : {0}.
        /// </summary>
        internal static string CouldNotFillText {
            get {
                return ResourceManager.GetString("CouldNotFillText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Component with the id &apos;{0}&apos; could not be found. The search is case sensitive..
        /// </summary>
        internal static string CouldNotFindControlWithID {
            get {
                return ResourceManager.GetString("CouldNotFindControlWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not layout the cells of the table grid with id &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string CouldNotLayoutGridCells {
            get {
                return ResourceManager.GetString("CouldNotLayoutGridCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; could not be parsed into a {1} instance..
        /// </summary>
        internal static string CouldNotParseValue_2 {
            get {
                return ResourceManager.GetString("CouldNotParseValue_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; could not be parsed into a {1} instance..
        /// </summary>
        internal static string CouldNotParseValue_21 {
            get {
                return ResourceManager.GetString("CouldNotParseValue_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; could not be parsed into a {1} instance. A value in the format &apos;{2}&apos; was expected..
        /// </summary>
        internal static string CouldNotParseValue_3 {
            get {
                return ResourceManager.GetString("CouldNotParseValue_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred whilst trying to extract the data..
        /// </summary>
        internal static string CouldNotSelectData {
            get {
                return ResourceManager.GetString("CouldNotSelectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested file could not be found at the specified path..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font &apos;{0} {1}&apos; has not been registered with the current resource section. Fonts must be registered with the current page or IResourceContainer before use. This is normally done with the PDFGraphics DrawString and DrawTextBlock methods..
        /// </summary>
        internal static string FontNotRegistered {
            get {
                return ResourceManager.GetString("FontNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PDFGraphics class only supports the TopDown DrawingOrigin.
        /// </summary>
        internal static string GraphicsOnlySupportsTopDownDrawing {
            get {
                return ResourceManager.GetString("GraphicsOnlySupportsTopDownDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table has not been measured or the referenced grid has been lost..
        /// </summary>
        internal static string GridIsNullNotMeasured {
            get {
                return ResourceManager.GetString("GridIsNullNotMeasured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CloseGrid method has not been called after adding cells to the table grid. .
        /// </summary>
        internal static string GridNotClosed {
            get {
                return ResourceManager.GetString("GridNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hierarchy is not complete. No parent exists that can create a graphics context for the requesting Component..
        /// </summary>
        internal static string InvalidCallToGetGraphicsForStructure {
            get {
                return ResourceManager.GetString("InvalidCallToGetGraphicsForStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unit cannot be instantiated with &apos;Empty&apos;, please specify the actual unit of measurement.
        /// </summary>
        internal static string InvalidEmptyUnits {
            get {
                return ResourceManager.GetString("InvalidEmptyUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XPath expression &apos;{0}&apos; could not be evaluated. Please check the statement..
        /// </summary>
        internal static string InvalidXPathExpression {
            get {
                return ResourceManager.GetString("InvalidXPathExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PDFComponentArangement has not been set on this Component before attempting to render. All Components must have their arrangement set before rendering..
        /// </summary>
        internal static string LayoutEngineHasNotSetArrangement {
            get {
                return ResourceManager.GetString("LayoutEngineHasNotSetArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The layout engine is already positioning a component. You cannot use the same engine to run more than one component at a time.
        /// </summary>
        internal static string LayoutEngineIsAlreadyWorking {
            get {
                return ResourceManager.GetString("LayoutEngineIsAlreadyWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The layout of component &apos;{0}&apos; failed. {1}.
        /// </summary>
        internal static string LayoutFailedForComponent {
            get {
                return ResourceManager.GetString("LayoutFailedForComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loading of an external file &apos;{0}&apos; is not supported in the base document class..
        /// </summary>
        internal static string LoadingOfExternalFilesNotSupported {
            get {
                return ResourceManager.GetString("LoadingOfExternalFilesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Measure and Arrange methods must be called on an object before it can be rendered..
        /// </summary>
        internal static string MeasureNotCalled {
            get {
                return ResourceManager.GetString("MeasureNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Measure and Arrange methods must be called on an object before it can be rendered..
        /// </summary>
        internal static string MeasureNotCalled1 {
            get {
                return ResourceManager.GetString("MeasureNotCalled1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NoOp count on the PDFComponentList has become unbalanced. Please ensure that the count is only incrementd or decrementd evenly..
        /// </summary>
        internal static string NoOpCountOutOfRange {
            get {
                return ResourceManager.GetString("NoOpCountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Type could be found in the namespace &apos;{1}&apos; that declares a component name &apos;{0}&apos;. Please check the file and required type..
        /// </summary>
        internal static string NoTypeFoundWithPDFComponentNameInNamespace {
            get {
                return ResourceManager.GetString("NoTypeFoundWithPDFComponentNameInNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid, sourced licence was not found that supports the restricted operation &apos;{0}&apos;. Please check your license agreement to ensure you are up to date..
        /// </summary>
        internal static string NoValidLicenceFoundForOperation {
            get {
                return ResourceManager.GetString("NoValidLicenceFoundForOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; cannot be null..
        /// </summary>
        internal static string NullArgument {
            get {
                return ResourceManager.GetString("NullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; cannot be null..
        /// </summary>
        internal static string NullArgument1 {
            get {
                return ResourceManager.GetString("NullArgument1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page break components are only supported at the root content level of a section..
        /// </summary>
        internal static string PageBreaksAreOnlySupportedAtTheRootSection {
            get {
                return ResourceManager.GetString("PageBreaksAreOnlySupportedAtTheRootSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent document cannot be null..
        /// </summary>
        internal static string ParentDocumentCannotBeNull {
            get {
                return ResourceManager.GetString("ParentDocumentCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent document of a template must implment the IPDFTemplateParser interface..
        /// </summary>
        internal static string ParentDocumentMustBeTemplateParser {
            get {
                return ResourceManager.GetString("ParentDocumentMustBeTemplateParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path resolution stack has become unbalanced and parsing cannot continue..
        /// </summary>
        internal static string PathStackIsUnbalanced {
            get {
                return ResourceManager.GetString("PathStackIsUnbalanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PDFType can only be initialized with a ASCII string {1} characters long. The string &apos;{0}&apos; is not the correct length..
        /// </summary>
        internal static string PDFTypeStringOnlyNChars {
            get {
                return ResourceManager.GetString("PDFTypeStringOnlyNChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required child element &apos;{0}&apos; was not found on the component definition &apos;{1}&apos;.
        /// </summary>
        internal static string RequiredChildElementNotFountOnElement {
            get {
                return ResourceManager.GetString("RequiredChildElementNotFountOnElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource container for the {0} component &apos;{1}&apos; was not found. This component can only be rendered as child of a resource container such as a Page or Section..
        /// </summary>
        internal static string ResourceContainerOfComponnetNotFound {
            get {
                return ResourceManager.GetString("ResourceContainerOfComponnetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The return type of expression &apos;{0}&apos; is a new XPath navigator. This cannot be assigned to a simple property..
        /// </summary>
        internal static string ReturnTypeOfXPathExpressionCannotBeNavigatorForPropertyEvaluation {
            get {
                return ResourceManager.GetString("ReturnTypeOfXPathExpressionCannotBeNavigatorForPropertyEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A template Component cannot be the root Component. It must be contained within another container..
        /// </summary>
        internal static string TemplateComponentCannotBeRoot {
            get {
                return ResourceManager.GetString("TemplateComponentCannotBeRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent Component of a template Component must be an instance of an IPDFContainerComponent.
        /// </summary>
        internal static string TemplateComponentParentMustBeContainer {
            get {
                return ResourceManager.GetString("TemplateComponentParentMustBeContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template generator has not been initialised. The InitTemplate method must be called before any instaniation..
        /// </summary>
        internal static string TemplateHasNotBeenInitialised {
            get {
                return ResourceManager.GetString("TemplateHasNotBeenInitialised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data stack has become unbalanced. Entries have been added or removed out of sequence..
        /// </summary>
        internal static string UnbalancedDataStack {
            get {
                return ResourceManager.GetString("UnbalancedDataStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The outline stack has become unbalanced. Entries have been added or removed out of sequence..
        /// </summary>
        internal static string UnbalancedOutlineStack {
            get {
                return ResourceManager.GetString("UnbalancedOutlineStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The style stack has become unbalanced. Entries have been added or removed out of sequence..
        /// </summary>
        internal static string UnbalancedStyleStack {
            get {
                return ResourceManager.GetString("UnbalancedStyleStack", resourceCulture);
            }
        }
    }
}
