//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perceiveit.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Perceiveit.Data.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema item could not be added to the collection because the Name was a null or empty string.
        /// </summary>
        internal static string CannotAddToSchemaWithNullOrEmptyName {
            get {
                return ResourceManager.GetString("CannotAddToSchemaWithNullOrEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A secondary where clause cannot be appended a no initial clause is present.
        /// </summary>
        internal static string CannotAppendWhereClauseWithoutInitial {
            get {
                return ResourceManager.GetString("CannotAppendWhereClauseWithoutInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This database statement builder cannot build CREATE statements for type &apos;{0}&apos;.
        /// </summary>
        internal static string CannotBuildCreateType {
            get {
                return ResourceManager.GetString("CannotBuildCreateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No DBStatement builder was returned from the factory for the database provider &apos;{0}&apos;..
        /// </summary>
        internal static string CannotCreateStatementBuilderForProvider {
            get {
                return ResourceManager.GetString("CannotCreateStatementBuilderForProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve the properties from the specified database. Check the inner exception for more details..
        /// </summary>
        internal static string CannotGetPropertiesFromDB {
            get {
                return ResourceManager.GetString("CannotGetPropertiesFromDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema cannot be specified if the tabel is not specified.
        /// </summary>
        internal static string CannotSpecifySchemaOwnerAndNotTable {
            get {
                return ResourceManager.GetString("CannotSpecifySchemaOwnerAndNotTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database engine does not support CLUSTERED or NON CLUSTERED indexes.
        /// </summary>
        internal static string CannotUseClusteredOrNonClustered {
            get {
                return ResourceManager.GetString("CannotUseClusteredOrNonClustered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Top N functions cannot be used as the inner text writers positon cannot be modified. .
        /// </summary>
        internal static string CannotUseTopAsInnerWriterNotSupportPosition {
            get {
                return ResourceManager.GetString("CannotUseTopAsInnerWriterNotSupportPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inner statements to a sub query can only be the root Query items - Select, insert, update, delete etc..
        /// </summary>
        internal static string CanOnlyUseQueriesInInnerSelects {
            get {
                return ResourceManager.GetString("CanOnlyUseQueriesInInnerSelects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialise the Xml stream. The element &apos;{0}&apos; was not a known Query element..
        /// </summary>
        internal static string CantDeserializeXML {
            get {
                return ResourceManager.GetString("CantDeserializeXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Exists is not supported by this database engine implementation.
        /// </summary>
        internal static string CheckExistsIsNotSupported {
            get {
                return ResourceManager.GetString("CheckExistsIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check NotExists is not supported by this Database engine implementation..
        /// </summary>
        internal static string CheckNotExistsIsNotSupported {
            get {
                return ResourceManager.GetString("CheckNotExistsIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The returned configuration element was not the correct type - expecting DBProfilerConfigElement..
        /// </summary>
        internal static string ConfigElementNotDBProfiler {
            get {
                return ResourceManager.GetString("ConfigElementNotDBProfiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a DBDatabase with an empty connection string..
        /// </summary>
        internal static string ConnectionStringNotSet {
            get {
                return ResourceManager.GetString("ConnectionStringNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connectionString attribute in the connection settings section with name &apos;{0}&apos; of the config file is not set.
        /// </summary>
        internal static string ConnectionStringNotSetInConfig {
            get {
                return ResourceManager.GetString("ConnectionStringNotSetInConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index reference wust have a valid Table reference set as its container inorder to uniquely identifiy it..
        /// </summary>
        internal static string ContainerNotSetOnIndexReference {
            get {
                return ResourceManager.GetString("ContainerNotSetOnIndexReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This database engine does not support the schema type &apos;{0}&apos;..
        /// </summary>
        internal static string DatabaseEngineDoesntSupportType {
            get {
                return ResourceManager.GetString("DatabaseEngineDoesntSupportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} database does not support the IF EXISTS or IF NOT EXISTS constructs for the schema type &apos;{1}&apos;.
        /// </summary>
        internal static string DBDoesntSupportIfExistsForThisType {
            get {
                return ResourceManager.GetString("DBDoesntSupportIfExistsForThisType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command could not be executed against the database. Please check the inner exception for more details..
        /// </summary>
        internal static string ExecutionFailedAgainstDatabase {
            get {
                return ResourceManager.GetString("ExecutionFailedAgainstDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider name &apos;{0}&apos; is not associated with a known DbProviderFactory.
        /// </summary>
        internal static string InvalidProviderNameForConnection {
            get {
                return ResourceManager.GetString("InvalidProviderNameForConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider name &apos;{0}&apos; is not associated with a known Perceiveit.Data.DBProviderImplementation. Add a new configuration element within the Perceiveit.Data/Implementations element to &apos;Register&apos; the provider name with a type..
        /// </summary>
        internal static string InvalidProviderNameForDBFactory {
            get {
                return ResourceManager.GetString("InvalidProviderNameForDBFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider name &apos;{0}&apos; set in the connection string section &apos;{1}&apos; is not associated with a known DbProviderFactory.
        /// </summary>
        internal static string InvalidProviderNameInConfigForConnection {
            get {
                return ResourceManager.GetString("InvalidProviderNameInConfigForConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On a MySql database the Auto Increment column must be the one and only primary key.
        /// </summary>
        internal static string MySqlAutoIncrementMustBeKey {
            get {
                return ResourceManager.GetString("MySqlAutoIncrementMustBeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column cannot be identified because the name has not been set.
        /// </summary>
        internal static string NoColumnNameSpecifiedForAField {
            get {
                return ResourceManager.GetString("NoColumnNameSpecifiedForAField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file does not contain a ConnectionStrings element with the name &apos;{0}&apos;. Please Add this connection to the configuration file, or change the name to a different connection..
        /// </summary>
        internal static string NoConfiguredConnectionWithName {
            get {
                return ResourceManager.GetString("NoConfiguredConnectionWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a DBDatabase with an empty connectionStringName value.
        /// </summary>
        internal static string NoConnectionStringName {
            get {
                return ResourceManager.GetString("NoConnectionStringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last item added to the create statement does not support default values.
        /// </summary>
        internal static string NoDefaultForColumn {
            get {
                return ResourceManager.GetString("NoDefaultForColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join does not have any comparion limits..
        /// </summary>
        internal static string NoJoinLimits {
            get {
                return ResourceManager.GetString("NoJoinLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join does not have a reference to a right hand table or sub query.
        /// </summary>
        internal static string NoJoinRightReference {
            get {
                return ResourceManager.GetString("NoJoinRightReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DbCommand does not contain a parameter with a matching generic name &apos;{0}&apos;..
        /// </summary>
        internal static string NoParameterWithGenericName {
            get {
                return ResourceManager.GetString("NoParameterWithGenericName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no registered DBProviderImplementation for the name &apos;{0}&apos;..
        /// </summary>
        internal static string NoProviderImplementationWithTheName {
            get {
                return ResourceManager.GetString("NoProviderImplementationWithTheName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No root or last table set to add the hint to.
        /// </summary>
        internal static string NoRootOrLastForHint {
            get {
                return ResourceManager.GetString("NoRootOrLastForHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table or view cannot be identified because the name has not been set..
        /// </summary>
        internal static string NoTableNameSpecifiedForATable {
            get {
                return ResourceManager.GetString("NoTableNameSpecifiedForATable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot serialize or de-serialize a Delegate parameter. Please use a constant parameter and set the value as required.
        /// </summary>
        internal static string NotSerializeDelegate {
            get {
                return ResourceManager.GetString("NotSerializeDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ole Db Create Table statement does not support default values on a column..
        /// </summary>
        internal static string OLEDbDoesNotSupportDefaultValues {
            get {
                return ResourceManager.GetString("OLEDbDoesNotSupportDefaultValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A profiler is already attached to this DBDatabase. Only one profiler is currently supported on a DBDatabase instance..
        /// </summary>
        internal static string ProfilerAlreadyAttached {
            get {
                return ResourceManager.GetString("ProfilerAlreadyAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DBProfilerCollection has changed between a call to Begin and End execution. The profiler data cannot be validated.
        /// </summary>
        internal static string ProfilerCollectionChangedBetweenStartAndEnd {
            get {
                return ResourceManager.GetString("ProfilerCollectionChangedBetweenStartAndEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The defined profiler factory with name &apos;{0}&apos; could not be created, or does not implement the IDBProfilerFactory interface.
        /// </summary>
        internal static string ProfilerFactoryTypeCouldNotBeInstantiated {
            get {
                return ResourceManager.GetString("ProfilerFactoryTypeCouldNotBeInstantiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of profiler factory with name &apos;{0}&apos; could not be found.
        /// </summary>
        internal static string ProfilerFactoryTypeNotFound {
            get {
                return ResourceManager.GetString("ProfilerFactoryTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A defined profiler in the configuration file does not have its name set. All profiers must have a non-empty name..
        /// </summary>
        internal static string ProfilerNameNotSetInConfig {
            get {
                return ResourceManager.GetString("ProfilerNameNotSetInConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a DBDatabase with an empty provider name.
        /// </summary>
        internal static string ProviderNameNotSet {
            get {
                return ResourceManager.GetString("ProviderNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The providerName attribute in the connection settings section with name &apos;{0}&apos; of the config file is not set.
        /// </summary>
        internal static string ProviderNameNotSetInConfig {
            get {
                return ResourceManager.GetString("ProviderNameNotSetInConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider name for a configured implementation is not set, or is an emty value. Please check the configuration section &apos;Perceiveit.Data/Implementations&apos;.
        /// </summary>
        internal static string ProviderNameNotSetInProviderImplementation {
            get {
                return ResourceManager.GetString("ProviderNameNotSetInProviderImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema column &apos;{0}&apos; cannot have a null or empty value..
        /// </summary>
        internal static string SchemaColumnCannotBeEmpty {
            get {
                return ResourceManager.GetString("SchemaColumnCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SchemaProvider could not find a column with the name &apos;{0}&apos;. This is a required column.
        /// </summary>
        internal static string SchemaColumnNotFound {
            get {
                return ResourceManager.GetString("SchemaColumnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creation and use of sequences is not supported on this database engine.
        /// </summary>
        internal static string SequenceCreationIsNotSupportedOnThisEngine {
            get {
                return ResourceManager.GetString("SequenceCreationIsNotSupportedOnThisEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLite does not support the ON construct when dropping table indexes. You must simply use the DROP INDEX on it&apos;s own without a table reference..
        /// </summary>
        internal static string SqlLiteDoesntSupportOnReferencesForIndexes {
            get {
                return ResourceManager.GetString("SqlLiteDoesntSupportOnReferencesForIndexes", resourceCulture);
            }
        }
    }
}
